### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by yikwing** [zhujian1989/flutter_study#4]
![image](https://user-images.githubusercontent.com/20245290/47603698-71ee8380-da22-11e8-8744-b0bed419a888.png)

![image](https://user-images.githubusercontent.com/20245290/47603686-3f448b00-da22-11e8-96a5-bed5938f010d.png)

**Comment by zhujian1989** [comment]
应该是sdk更新了，初始化改变了

**Comment by zhujian1989** [comment]
先注释掉，不影响demo，这是我之前测试用的代码，sdk更新后构造方法改变了

**Comment by zhujian1989** [comment]
如果是想看插件话数据相关的，你可以试试这个https://www.jianshu.com/p/5aa4f2a7ed0e
